// This file was generated by Prisma and is kept for reference
// NOTE: This config is only used by Prisma CLI v6+ with the new config format
// For older versions, use prisma/schema.prisma directly

// Export empty object to satisfy TypeScript if this file is included in build
export {};
